### ISSUE TITLE
Emit /alive and /ready endpoints

### ISSUE THREAD

**Issue by milsonian** [k8guard/k8guard-action#10]
* Add /alive and /ready endpoints, so we can do proper k8s liveliness & readiness checks
  * /ready should only be healthy when connected to Cassandra and Kafka

**Comment by y-taka-23** [comment]
Excuse me but could you clarify the requirements: What the `/ready` endpoint is for? 

The `k8guard-action` (at least for now) doesn't accept any inbound accesses from the outside by design, and actually we don't have `k8guard-action-svc.yml`. I'm afraid that only `/alive` is needed.

**Comment by milsonian** [comment]
Largely for future-proofing/best practice, but it does have some advantages - e.g. if the dependencies are unavailable, we can know that via events but k8s will keep the action processes running which are otherwise healthy - rather than killing/thrashing them.

This reminds me though we should probably consider action's behavior in these conditions (can it actually 'recover'; if not we may just want liveliness for now).  Thoughts @medyagh @rmb938 ?

**Comment by medyagh** [comment]
@y-taka-23 I think you are on to something and it is a good point we don't have a service for action !  I agree with your suggestion  `/live` would be sufficient for action microservice, with the condition that /live means it is capable of connecting to cassandra and kafka and if it is not I would try again with retry exponential backoff strategy and then fail, maybe rertry up to 5 min before failing.

**Comment by y-taka-23** [comment]
@milsonian @medyagh Thank you for your comments!

The exponential backoff strategy sounds cool. Nevertheless I'm afraid that if we implement such a retrying logic in the `/alive` endpoint itself, it can conflict with periodic execution of Probe.

How is creating `/alive` to check the Cassandra/Kafka connectivity simply at once, and control retrying in Kubernetes side, i.e. by `periodSeconds` and `failureThreshold`? Of course it is not exponential, but we can keep the things simple.

**Comment by milsonian** [comment]
Good point @y-taka-23 I think that's totally reasonable for now.  Assuming we check deps at start, we will get safe backoff from k8s itself on CrashLoopBackoff too.

**Comment by medyagh** [comment]
@y-taka-23 agreed ! lets add that to the minikube example then. thanks.

**Comment by y-taka-23** [comment]
@milsonian @medyagh Okay, so I'd like to go in this direction.
